ProgressTracker/ProgressTracker/Models/Student.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Events = new HashSet<Event>();
            this.MeetingRecords = new HashSet<MeetingRecord>();
            this.Milestones = new HashSet<Milestone>();
        }
    
        public string UserID { get; set; }
        public string Course { get; set; }
        public string StudyYear { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingRecord> MeetingRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestone> Milestones { get; set; }
    }
}

ProgressTracker/ProgressTracker/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ProgressTracker.Models;

namespace ProgressTracker.Controllers
{
    public class StudentsController : Controller
    {
        private ProgressTrackerEntities db = new ProgressTrackerEntities();
        public ActionResult Choose()
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email");
                return View();
            }
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Choose([Bind(Include = "StudentNumber,Course,StudyYear,ProjectName")] Student student)
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                if (ModelState.IsValid)
                {
                    db.Students.Add(student);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email", student.UserID);
                return View(student);
            }
        }

        //GET: ProjectSupervisors/Edit/5
        public ActionResult Select(string id, string StudentNumber)
        {
            string studID = StudentNumber;
            using (var db = new ProgressTrackerEntities())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ProjectSupervisor supervisor = db.ProjectSupervisors.Find(id);
                Student student = db.Students.Find(id);
                if (supervisor == null)
                {
                    return HttpNotFound();
                }
                string selectedSup = supervisor.UserID;




                Allocation allocation = new Allocation();
                allocation.StaffNumber = id;
                allocation.StudentNumber = studID;
                db.Allocations.Add(allocation);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

        }




        public ActionResult ChooseSupervisors(string Id)
        {

            ViewBag.studentId = Id;
            var SelectedList = new List<SelectListItem>();

            ProjectSupervisor projectSupervisor = new ProjectSupervisor();
            List<AspNetUser> data = new List<AspNetUser>();
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {

                var supervisors = from rowS in db.AspNetUsers
                                  join rowSupervisor in db.ProjectSupervisors on rowS.Id equals rowSupervisor.UserID
                                  where rowS.Id == rowSupervisor.UserID
                                  //select new AspNetUser { Id = rowSupervisor.UserID };
                                  select rowS;


                data = supervisors.ToList();
                ViewBag.Students = data;

                return View(data);
            }


        }



        // GET: Students
        public ActionResult Index()
        {
            var students = db.Students.Include(s => s.AspNetUser);
            return View(students.ToList());
        }
        public ActionResult SelectStudent()
        {
            List<AspNetUser> students = new List<AspNetUser>();

            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                var allstuds = from rowS in dc.AspNetUsers
                               join rowStudents in dc.Students on rowS.Id equals rowStudents.UserID
                               where rowS.Id == rowStudents.UserID
                               select rowS;
                students = allstuds.ToList();
                ViewBag.students = students;
                return View(allstuds.ToList());
            }
        }

        public ActionResult ViewAMySupervisor(string id)
        {
            List<AspNetUser> supervisor = new List<AspNetUser>();
            var studId = id;
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                var sups = from rowS in dc.AspNetUsers
                           join rowR in dc.Allocations on rowS.Id equals rowR.StaffNumber
                           where rowR.StudentNumber == studId
                           select rowS;
                supervisor = sups.ToList();
            }
            return View(supervisor);
        }

        public ActionResult ViewMySupervisor(string id)
        {
            List<AspNetUser> supervisor = new List<AspNetUser>();
            var studId = User.Identity.GetUserId();
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                var sups = from rowS in dc.AspNetUsers
                           join rowR in dc.Allocations on rowS.Id equals rowR.StaffNumber
                           where rowR.StudentNumber == studId
                           select rowS;
                supervisor = sups.ToList();
            }
            return View(supervisor);
        }




        public ActionResult ViewAllStudents()
        {
            List<AspNetUser> students = new List<AspNetUser>();
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                var allstuds = from rowS in dc.AspNetUsers
                               join rowStudents in dc.Students on rowS.Id equals rowStudents.UserID
                               where rowS.Id == rowStudents.UserID
                               select rowS;
                students = allstuds.ToList();

                return View(students);
            }
        }


        // GET: Students/Details/5
        public ActionResult Details(string id)
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Student student = db.Students.Find(id);
                if (student == null)
                {
                    return HttpNotFound();
                }
                return View(student);
            }
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email");
                return View();
            }
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentNumber,Course,StudyYear,ProjectName")] Student student)
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                if (ModelState.IsValid)
                {
                    db.Students.Add(student);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email", student.UserID);
                return View(student);
            }
        }

        // GET: Students/Edit/5
        public ActionResult Edit(string id)
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Student student = db.Students.Find(id);
                if (student == null)
                {
                    return HttpNotFound();
                }
                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email", student.UserID);
                return View(student);
            }
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentNumber,Course,StudyYear,ProjectName")] Student student)
        {
            using (ProgressTrackerEntities dc = new ProgressTrackerEntities())
            {
                if (ModelState.IsValid)
                {
                    db.Entry(student).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.StudentNumber = new SelectList(db.AspNetUsers, "Id", "Email", student.UserID);
                return View(student);
            }
        }




        // GET: Students/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5

ProgressTracker/ProgressTracker/Views/Students/AddProject.cshtml
@model ProgressTracker.Models.Student

@{
    ViewBag.Title = "AddProject";
}

<h2>Please enter your project name as allocated to you:</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentNumber)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudyYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudyYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudyYear, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Students/ChooseSupervisors.cshtml
@model IEnumerable<ProgressTracker.Models.AspNetUser>

@{
    ViewBag.Title = "ChooseSupervisors";
}

<h2>ChooseSupervisors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
      
        
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Picture)
        </td>
        <td>
            @Html.ActionLink("Select", "Select", new { id=item.Id, StudentNumber= ViewBag.studentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ProgressTracker/ProgressTracker/Views/Students/Create.cshtml
@model ProgressTracker.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentNumber, "StudentNumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudyYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudyYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudyYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Students/Delete.cshtml
@model ProgressTracker.Models.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudyYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudyYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProgressTracker/ProgressTracker/Views/Students/Details.cshtml
@model ProgressTracker.Models.Student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudyYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudyYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentNumber }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProgressTracker/ProgressTracker/Views/Students/Edit.cshtml
@model ProgressTracker.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudyYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudyYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudyYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Students/Index.cshtml
@model IEnumerable<ProgressTracker.Models.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudyYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudyYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserID })
        </td>
    </tr>
}

</table>

ProgressTracker/ProgressTracker/Views/Students/Select.cshtml
@model ProgressTracker.Models.AspNetUser

@{
    ViewBag.Title = "Select";
}

<h2>Select</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownList("Supervisor", new SelectList(ViewBag.Students, "Name", "Name"))
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Assign" onclick="location.href='@Url.Action("Select", "Students")'" />
                @*   <input type="submit" value="Assign" class="btn btn-default" />*@
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Students/ViewAMySupervisor.cshtml
@model IEnumerable<ProgressTracker.Models.AspNetUser>

@{
    ViewBag.Title = "ViewAMySupervisor";
}

<h2>ViewAMySupervisor</h2>



<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Picture)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

ProgressTracker/ProgressTracker/Views/Students/ViewAllStudents.cshtml
@model IEnumerable<ProgressTracker.Models.AspNetUser>

@{
    ViewBag.Title = "ViewAllStudents";
}

<h2>View All Students</h2>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Picture)
            </td>

            <td>
                @Html.ActionLink("Assign Supervisors", "ChooseSupervisors", new { id = item.Id }) |
                @Html.ActionLink("View Supervisors", "ViewAMySupervisor", new { id = item.Id }, new { @class="dialog"}) |
                
            </td>
        </tr>
    }

</table>

<script type="text/javascript">
    $(function () {
        $('a.dialog').click(function () {
            var url = $(this).attr('href');
            var dialog = $('<div style="display:none"></div>').appendTo('body');
            dialog.load(url, {},
                function (responseText, textStatus, XMLHttpRequest) {
                    dialog.dialog({
                        close: function (event, ui) {
                            dialog.remove();
                        }
                    });
                });
            return false;
        });
    });
</script>

ProgressTracker/ProgressTracker/Views/Students/ViewMySupervisor.cshtml
@model IEnumerable<ProgressTracker.Models.AspNetUser>

@{
    ViewBag.Title = "ViewMySupervisor";
}

<h2>My Supervisor(s)</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
      
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Picture)
        </td>
      
        <td>
          
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
          
        </td>
    </tr>
}

</table>