ProgressTracker/ProgressTracker/Models/Milestone.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Milestone()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public string Text { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ProjectNumber { get; set; }
        public string Type { get; set; }
        public string MilestoneID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<double> Progress { get; set; }
        public int Id { get; set; }
        public string StudentNumber { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> InProgress { get; set; }
        public Nullable<bool> ToDo { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Student Student { get; set; }
    }
}

ProgressTracker/ProgressTracker/Controllers/MilestonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ProgressTracker.Models;

namespace ProgressTracker.Controllers
{
    public class MilestonesController : Controller
    {
        private ProgressTrackerEntities db = new ProgressTrackerEntities();
        

        // GET: Milestones
        public ActionResult Index()
        {
            var milestones = db.Milestones.Include(m => m.Student);
            return View(milestones.ToList());
        }

        // GET: Documents/Create
        public ActionResult Upload(int? id)
        {
            using (var db = new ProgressTrackerEntities())
            {
                ViewBag.Id = id;
            }
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload([Bind(Include = "DocumentID,DocumentName,Path,Id,MilestoneID")] Document document, IEnumerable<HttpPostedFileBase> File, int id)
        {
            using (var db = new ProgressTrackerEntities())
            {
                
                    if (ModelState.IsValid)
                    {
                    
                        document.Path = "/UploadedFiles/" + File.First().FileName;
                        document.MilestoneID = id;
                         document.DocumentName = document.DocumentName;
                        db.Documents.Add(document);

                        db.SaveChanges();
                   
                    return RedirectToAction("Index");
                    }
                
                ViewBag.Id = new SelectList(db.Milestones, "Id", "Text", document.Id);
            }
            return View(document);
        }


        public ActionResult UploadFile(int? id)
        {
            using (var db = new ProgressTrackerEntities())
            {
                ViewBag.Id = id;
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocumentID,DocumentName,FileExtension,ContentType")] Document document, IEnumerable<HttpPostedFileBase> file, int id)
        {

            var _path = "";

            Milestone milestone = new Milestone();
            using (var db = new ProgressTrackerEntities())
            {

                if (ModelState.IsValid)
                {

                    document.Id = id;
                    //  document.DocumentName=
                    // db.SaveChanges();

                    foreach (var doc in file)
                    {
                        document = new Document();
                        if (doc != null && doc.ContentLength > 0)
                        {
                            // string _FileName = Path.GetFileName(doc.FileName);
                            _path = Path.Combine(Server.MapPath("~/UploadedFiles"), document.DocumentName);

                            doc.SaveAs(_path);

                            // document.DocumentName = _FileName;
                            document.Path = _path;
                            document.Id = id;

                            db.Documents.Add(document);
                            db.SaveChanges();
                        }
                        ViewBag.Message = "File Uploaded Successfully!!";
                        return View();
                    }



                }

                ViewBag.Message = "File upload failed!!";
                return View();

            }
        }
        public ActionResult ViewMilestones()
        {
            List<Milestone> data = new List<Milestone>();
            var userID = User.Identity.GetUserId();
            using (var db = new ProgressTrackerEntities())
            {
                var milestones = from rowM in db.Milestones
                                 where rowM.StudentNumber == userID
                                 select rowM;
                data = milestones.ToList();

            }
            return View(data);

        }

        public ActionResult ViewStudentMilestones(string id)
        {
            List<Milestone> data = new List<Milestone>();
            Student student = new Student();
            var studID = id;
            using (var db = new ProgressTrackerEntities())
            {
                var milestones = from rowM in db.Milestones
                                 where rowM.StudentNumber == studID
                                 select rowM;
                data = milestones.ToList();

            }
            return View(data);

        }

  


        // GET: Milestones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Milestone milestone = db.Milestones.Find(id);
            if (milestone == null)
            {
                return HttpNotFound();
            }
            return View(milestone);
        }

        // GET: Milestones/Create
        public ActionResult AddMilestone()
        {
            ViewBag.MilestoneID = new SelectList(db.Students, "StudentNumber", "Course");
            return View();
        }

        // POST: Milestones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMilestone([Bind(Include = "MilestoneID,Text,StartDate,Duration,ProjectNumber,Type,ParentId,Progress,Id,StudentNumber")] Milestone milestone)
        {
            var userID = User.Identity.GetUserId();
            using (var db = new ProgressTrackerEntities())
            {
                if (ModelState.IsValid)
                {
                   
                    milestone.StudentNumber = userID;
                    if(milestone.Progress==1)
                    {
                        milestone.Status = "Completed";
                        milestone.Completed = true;
                    }
                    else if(milestone.Progress>0 &&milestone.Progress<1)
                    {
                        milestone.Status = "In-Progress";
                        milestone.InProgress = true;
                    }
                    else
                    {
                        milestone.Status = "To-Do";
                        milestone.ToDo = true;
                    }
                    
                    
                    
                    db.Milestones.Add(milestone);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.MilestoneID = new SelectList(db.Students, "StudentNumber", "Course", milestone.MilestoneID);
            return View(milestone);
        }

        // GET: Milestones/Edit/5
        public ActionResult Edit(int? id)
        {
            Milestone milestone = new Milestone();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using(var db=new ProgressTrackerEntities())
            {
                milestone = db.Milestones.Find(id);

            }
            if (milestone == null)
            {
                return HttpNotFound();
            }
            //ViewBag.MilestoneID = new SelectList(db.Students, "StudentNumber", "Course", milestone.MilestoneID);
            return View(milestone);
        }

        // POST: Milestones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MilestoneID,Text,StartDate,Duration,ProjectNumber,Type,ParentId,Progress,Id,StudentNumber")] Milestone milestone)
        {
            var userID = User.Identity.GetUserId();
            using (var db = new ProgressTrackerEntities())
            {
                if (ModelState.IsValid)
                {
                    milestone.StudentNumber = userID;
                    db.Entry(milestone).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.MilestoneID = new SelectList(db.Students, "StudentNumber", "Course", milestone.MilestoneID);
            return View(milestone);
        }

        // GET: Milestones/Delete/5
        public ActionResult Delete(int? id)
        {
            var userID = User.Identity.GetUserId();
            using (var db = new ProgressTrackerEntities())
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Milestone milestone = db.Milestones.Find(id);
                if (milestone == null)
                {
                    return HttpNotFound();
                }
                return View(milestone);
            }
        }

        // POST: Milestones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Milestone milestone = db.Milestones.Find(id);
            db.Milestones.Remove(milestone);
            db.SaveChanges();

ProgressTracker/ProgressTracker/Controllers/UploadController.cs
using Microsoft.AspNet.Identity;
using ProgressTracker.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgressTracker.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {

            return View();
        }




        
    }
}

ProgressTracker/ProgressTracker/Views/Milestones/AddMilestone.cshtml
@model ProgressTracker.Models.Milestone

@{
    ViewBag.Title = "AddMilestone";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>




     

       

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Milestones/Create.cshtml
@model ProgressTracker.Models.Milestone

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Milestone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MilestoneID, "MilestoneID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MilestoneID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MilestoneID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Progress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Progress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Progress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Milestones/Delete.cshtml
@model ProgressTracker.Models.Milestone

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ProjectNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectNumber)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Progress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.Student.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Course)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProgressTracker/ProgressTracker/Views/Milestones/Details.cshtml
@model ProgressTracker.Models.Milestone

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Milestone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ProjectNumber)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.ProjectNumber)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Progress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.Student.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Course)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProgressTracker/ProgressTracker/Views/Milestones/Index.cshtml
@model IEnumerable<ProgressTracker.Models.Milestone>

@{
    ViewBag.Title = "Index";
}

<h2>Milestones</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ProjectNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParentId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Progress)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.StudentNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.Course)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ProjectNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParentId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Progress)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.StudentNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.Course)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
            @Html.ActionLink("Upload File", "Upload", new { id = item.Id })
        </td>
    </tr>
}

</table>

ProgressTracker/ProgressTracker/Views/Milestones/Upload.cshtml
@model ProgressTracker.Models.Document

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>

@using (Html.BeginForm("Upload","Milestones",FormMethod.Post,new { id="form",enctype= "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Document</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
            @Html.LabelFor(model => model.DocumentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
            @Html.LabelFor(model => model.DocumentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentName, "", new { @class = "text-danger" })
            </div>
        </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="File" accept="UploadedFiles/*" multiple />

            @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Id, "Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.MilestoneID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MilestoneID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MilestoneID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProgressTracker/ProgressTracker/Views/Milestones/ViewMilestones.cshtml
@model IEnumerable<ProgressTracker.Models.Milestone>

@{
    ViewBag.Title = "View Milestones";
}

<div id="container">
    <h2>Milestones</h2>
    <a style="" href="@Url.Action("Index", "Gantt")">
        <img src="@Url.Content("~/Images/Icons/Sign_Add_Icon_32.png")" align="right" />
    </a>
</div>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration) <p>(Day(s))</p>
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Progress)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>



        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Progress)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>

            <td>
                <a href="@Url.Action("Edit", "Milestones", new { id = item.Id })">
                    <img src="@Url.Content("~/Images/Icons/Edit_Icon_32.png")" />
                </a>|
                <a href="@Url.Action("Delete", "Milestones", new { id = item.Id })">
                    <img src="@Url.Content("~/Images/Icons/Delete_Icon_32.png")" />
                </a>|

                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Upload File", "Upload", new { id = item.Id })
            </td>
        </tr>

    }

</table>